config/routes.rb
Rails.application.routes.draw do
  root "users#index"

  resources :users, only: [:show, :index, :new, :create] do 
    resources :appointments do
    	resources :feedbacks, except: [:edit, :delete]
	end
  end
  resources :calendars, only: [:index]
  resources :sessions, only: [:new, :create, :destroy]
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  
end

app/models/appointment.rb
class Appointment < ActiveRecord::Base
  has_many :feedbacks
  belongs_to :mentor, class_name: "User"
  belongs_to :student, class_name: "User"

  validates :start_time, :topic, presence: true

  # validate :time_is_in_future

  def time_is_in_future
    if start_time < Time.now
      @errors.add(:start_time, "start_time must be in the future")
    end
  end

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :user
  belongs_to :appointment

  validates :body, :rating, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  has_many :mentor_sessions, class_name: "Appointment", foreign_key: "mentor_id"
  has_many :study_sessions, class_name: "Appointment", foreign_key: "student_id"
  has_many :feedbacks

  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  
  def index
  end

  def new
    @appointment = Appointment.new
  end

  def show
    
    @user = User.find(params[:user_id])
     if @user.user_type == "mentor"
       @appointment = @user.mentor_sessions.find(params[:id])
     else
      @appointment = @user.study_sessions.find(params[:id])
     end
  
  end


  def create    
    @user = User.find(params[:user_id])

    start_time = params[:appointment][:start_time]
    end_time = params[:appointment][:end_time]
    topic = params[:appointment][:topic]

    appointment = Appointment.new(mentor_id: params[:user_id], 
                                  start_time: start_time, 
                                  end_time: end_time, 
                                  topic: topic )
    
    if appointment.save
       redirect_to user_path(@user)
       flash[:alert] = "Session slot created successfully!"
    end
  #   args = params[:appointment]
  #   args[:mentor_id] = params[:user_id]
    
  #   args = params[:appointment]
  #  args[:mentor_id] = params[:user_id]
   
  end

  def update
      appointment = Appointment.find(params[:id])
      appointment.update(student_id: params[:user_id])
      redirect_to user_path(params[:user_id])
  end
  
# end

  # appointment = Appointment.new(mentor_id: params[:user_id], start_time: start_time, end_time: end_time, topic: topic )
  
  # if appointment.save
  #    redirect_to user_path(@user)
  #    flash[:alert] = "Session slot created successfully!"
  # end
  
  # end

  # def update
  #     appointment = Appointment.find(params[:id])
  #     appointment.update(student_id: params[:user_id])
  #     redirect_to user_path(params[:user_id])
  # end
  
end

app/controllers/calendars_controller.rb
class CalendarsController < ApplicationController

	def index
		if @current_user
			@user = current_user
		end
	end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

	def index
		
	end

	def new
		@feedback = Feedback.new
	end

	def create
		@user = User.find(params[:user_id])
		@appointment = Appointment.find(params[:appointment_id])

		
		@feedback = Feedback.new(body: params[:feedback][:body], 
								appointment_id: @appointment.id, 
								user_id: @user.id, 
								rating: params[:feedback][:rating])

		if @feedback.save
			redirect_to user_appointment_path(@user.id, @appointment.id)
		else
			flash[:alert] = "Please fill out all fields"
			redirect_to user_appointment_path(@user.id, @appointment.id)
		end
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by_email(params[:email])
    # If the user exists AND the password entered is correct.
    if @user && @user.authenticate(params[:password])
      # Save the user id inside the browser cookie. This is how we keep the user 
      # logged in when they navigate around our website.
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
    # If user's login doesn't work, send them back to the login form.
      flash[:errors] = 'Invalid email or password'
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
	layout "application"
	# before_action :user_params, only: [:create]

	def new
		@user = User.new
	end

	def index
	end

	def show
		@user = User.find(params[:id])
	end


def create
	@user = User.new(user_params)

	if @user.save
		session[:user_id]=@user.id
		redirect_to user_path(@user)
	else
		flash[:alert] = "Please fill out all fields"
		render 'new'
	end
end

private
def user_params
	params.require(:user).permit(:name,:password,:email,:telephone,:user_type)
end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def login(user)
		session[:user_id]=user.id
	end

	def logged_in?
		session[:user_id]
	end

	def current_user
		user = User.find_by(id:session[:user_id])
	end

end

app/views/appointments/show.html.erb
<div>
	<br>
	<div class="well">
		<strong>Title: </strong><%= @appointment.topic%><br>
		<strong>Mentor: </strong><%= @appointment.mentor.name %><br>
		<strong>Student:</strong> <%= @appointment.student.name if @appointment.student_id != nil%><br>	
	</div>
</div>
<br>
<br>



<div class="well">
	<strong>Feedbacks:</strong>
	<% @appointment.feedbacks.each do |feedback| %>
  		<ul>
    		<li><p><%= feedback.body %></p></li>
  		</ul>
	<% end %>
</div>
<br>
<br>
<br>

<% if @appointment.start_time.past? %>
	<%= render 'feedback/form' %>
  <% end %>

app/views/calendars/index.html.erb
<% if current_user %>


  <% open_sessions = Appointment.all.select{|apt| apt.student_id == nil} %>

  <%= week_calendar events: Appointment.all do |date, appointments| %>
    <b><%= date %></b>

    <% appointments.each do |appointment| %>
      <div>
        <br>
        <%= appointment.start_time.strftime("%I:%M%p") %>
        Mentor: <%= appointment.mentor.name %>
        Topic: <%= appointment.topic %>

         <% if current_user.user_type == 'student' && open_sessions.include?(appointment) %>
          <%= button_to "Signup", user_appointment_path(current_user.id, session.id), method: "put", :class => 'appointment'  %> 
        <% end %>
        <hr>
        <br> 
        <br>
      </div>
    <% end %>

  <% end %>

<% else %>
  <br>
  Login to see the calendar!

<% end %>

app/views/feedback/_form.html.erb
<%= form_for :feedback, url: user_appointment_feedbacks_path(@user, @appointment), method:'post' do |f|  %>
	<p><strong> Leave Feedback:</strong></p>
	<%= "Select your rating:" %>
	<%= f.select :rating, [1, 2,3,4,5]%>
	<br>
	<br>
	<%= f.text_area( :body ,size: "100x15") %>
	<%= f.submit "Submit"  %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>MenMen</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css"></script>
	</head>

	<body>
	<%= render 'partials/header' %>

	<%= yield %>

	</body>
</html>

app/views/partials/_header.html.erb
<nav class="navbar navbar-inverse f_color" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <!-- <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      
    </div>
    <%= link_to image_tag("logo2.png", alt: "logo"), '/', class: 'navbar-brand' %>
    <!-- <a class="navbar-brand" href="#"><img src="../logo2.png"></a> -->
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-1">
      <% if logged_in? %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= button_to "Profile", user_path(current_user.id), method: "get", :class => 'navbar-link', :class => "btn btn-sm btn-margin-left"  %></li>
          
          <li><%= button_to "Calendar", calendars_path,method: "get", :class => 'navbar-link', :class => "btn btn-sm btn-margin-left" %></li>

          <li><%= button_to "Logout", session_path(current_user.id), method: "delete", :class => 'navbar-link', :class => "btn btn-sm btn-margin-left" %></li>

        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="#"><strong><%= current_user.email %></strong>(<%= current_user.user_type %>)</a></li>
          <!-- <li><a href="#">Link</a></li>
          <li><a href="#">Link</a></li> -->
        </ul>
      <% else %>
        <ul class="nav navbar-nav navbar-left">
          <li><%= button_to "Sign up", new_user_path, method: "get", :class => 'navbar-link', :class => "btn btn-sm btn-margin-left" %></li>

          <li><%= button_to "Login", new_session_path, method: "get", :class => 'navbar-link', :class => "btn btn-sm btn-margin-left" %></li>
        </ul>
      <% end %>
        
    </div><!-- /.navbar-collapse -->
</nav>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/_form.html.erb
<h1>Create new account</h1>

<%= form_for :user, url: users_path, method: 'post' do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>
  <p>
    <%= f.label :telephone %><br>
    <%= f.text_field :telephone %>
  </p>
 
  <section>
    <%= f.radio_button :user_type, 'student' %>Student<br/>
    <%= f.radio_button :user_type, 'mentor' %>Mentor<br/>
  </section>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/index.html.erb
<div class='container gray'>
	<div class='logo'><%= image_tag("logo2.png") %></div>
	<p>We offer free mentor scheduling system to our members</p>
	<p>Our teachers offer 30 minute sessions in different topic</p>
	<p>Students can login, choose a open spot and register for that spot</p>
	<p>Students have a calander that shows all the events and in their</p>
	<p>profile page they can see all the sessions they have registered for</p>

</div>

<section class="bg-1 text-center">

</section>

<br>
<br>
<br>
<br>

<div class='container gray'>
	<p>If you have not created an account yet, it's time to do it now</p>
	<p>With creating a new account you get access to all of our mentors and </p>
	<p>you will be able to book mentor session with them</p>

</div>

<br>
<br>
<br>
<br>

<section class="bg-2 text-center">

</section>


<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/users/new.html.erb
<%= render "users/form" %>

app/views/users/show.html.erb
<p>
  <img height="100px" width="100" src="<%= @user.avatar %>" />
  <strong>Hello </strong><%= @user.name %><br>  
</p>

<!-- <h3><strong>Upcoming Appointments:</strong></h3> -->
<br>
<br>
<br>
<!-- <div class="container"> -->
<div class="im-centered">
<div class="row">

  <% if @user.user_type == 'mentor' %>
  
  <div class="col-md-4">
  <!-- <div class="panel panel-default"> -->
  <div class="well">
   <h3><strong>Upcoming Appointments:</strong></h3>
    <% @user.mentor_sessions.each do |mentor_session| %>
      <% if mentor_session.start_time.future? %>
        <ul>
            <li>
            Start time: <%= link_to mentor_session.start_time, user_appointment_path(@user.id,mentor_session.id) %>
            End time: <%= mentor_session.start_time + 30.minutes %>
          </li>
        </ul>
      <% end %>
    <% end %>
  </div>
  </div>
  <!-- </div> -->
  

  <div class="col-md-4">
  <!-- <div class="panel panel-default"> -->
  <div class="well">
    <h3><strong>Past Appointments:</strong></h3>
    <% @user.mentor_sessions.each do |mentor_session| %>
      <% if !mentor_session.start_time.future? %>
      <ul>
          <li>
          Start time: <%= link_to mentor_session.start_time, user_appointment_path(@user.id,mentor_session.id) %>
          End time: <%= mentor_session.start_time + 30.minutes %>
        </li>
      </ul>
      <% end %>
    <% end %>
  </div>
  </div>
  <!-- </div> -->

</div>
</div>
<!-- </div> -->

<br>
<br>
<br>
<br>
<br>

  <p><strong> Create new available spots for students:</strong></p>
  <%= form_for :appointment, url: user_appointments_path(@user.id), method: 'post' do |f| %> 
    <p>
      <%= f.label :start_time %><br>
      <%=  f.datetime_local_field :start_time %>
    </p>

    <p>
      <%= f.label :topic %><br>
      <%= f.text_field :topic %>
    </p>
   
    <p>
      <%= f.label :create %><br>
      <%= f.submit %>
    </p>
  <% end %>


<% else %>

  <h3><strong>Upcoming Appointments:</strong></h3>
    <% @user.study_sessions.each do |study_session| %>
      <% if study_session.start_time.future? %>
        <ul>
            <li>
            Start time: <%= link_to study_session.start_time, user_appointment_path(@user.id,study_session.id) %>
            End time: <%= study_session.start_time + 30.minutes %>
          </li>
        </ul>
      <% end %>
    <% end %>


    <h3><strong>Past Appointments:</strong></h3>
    <% @user.study_sessions.each do |study_session| %>
      <% if !study_session.start_time.future? %>
      <ul>
          <li>
          Start time: <%= link_to study_session.start_time, user_appointment_path(@user.id,study_session.id) %>
          End time: <%= study_session.start_time + 30.minutes %>
        </li>
      </ul>
      <% end %>
    <% end %>

  <br>
  <br>
  

  <h3>Appointments Available:</h3>
    <% open_sessions = Appointment.all.select{|apt| apt.student_id == nil} %>
    <% open_sessions.each do |session| %>
      <div>
        <span><%= session.mentor.name %></span> on
            <%= session.topic %>
      </div>
      <div>
        <%= button_to "Signup", user_appointment_path(current_user.id, session.id), method: "put", :class => 'appointment'  %>
      </div>
    <% end %>
<% end %>